[config]
transactions = 10000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "OrbitFlare"
url = "http://ams.rpc.orbitflare.com:10000"
kind = "yellowstone"
x_token = "ORBIT-YPUBAK-893760-776448"
#url = "http://ams.jetstream.orbitflare.com:80"
#url = "http://207.90.225.163:9999"
#kind = "shredstream"

[[endpoint]]
name = "Triton"
url = "https://riptide.rpcpool.com"
x_token = "a50c8dba-ba2a-423a-9d45-5bd5210e1304"
#kind = "shredstream"
kind = "yellowstone"
